service: mono-repo-billing-api

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.seed-frank-playground.download
    basePath: billing

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

functions:
  main:
    handler: handler.main
    events:
      - http:
          path: /
          method: get
          cors: true

