service: mono-repo-search-api

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

functions:
  main:
    handler: handler.main
    events:
      - http:
          path: /
          method: get
          cors: true

