service: mono-repo-search-api

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.seed-frank-playground.download
    basePath: search

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1

functions:
  main:
    handler: handler.main
    events:
      - http:
          path: /
          method: get
          cors: true

